### PR TITLE
Use strict equality check by default

### LINKED ISSUE #67: Prefer strict equality comparison over the regular one
Hello and thank you for your wonderful tool.

**The problem**

The Observable I'm testing returns an object. That object is not allowed to have values explicitly set to `undefined` — in case the value does not exist, I want to skip the field instead.

My Marble tests reflect that. I expect only one property.

```ts
const expected$ = m.cold(expectedM, {
  a: {
    name: 'Bob',
  },
});

m.expect(actual$).toBeObservable(expected$);
```

However, the output emitted by `actual$` looks like that:

```ts
  a: {
    name: 'Bob',
    age: undefined,
  },
```

This change was not detected by Jest, but it did break my code.

**The solution**

When performing deep equality comparison. prefer `toStrictEqual` over `toEqual`.

If we replace `toEqual` with `toStrictEqual`, my excess properties are detected, which makes the tests fail as expected. This change would need to be made here:

https://github.com/cartant/rxjs-marbles/blob/75b646c92765e24f42119ba1e2855946ff391811/source/jest/index.ts#L43

If you agree with that change, I can open a PR and get it done — just say the word.

### PR DESCRIPTION
**Pull request by karol-majewski**
Fixes #67.

### CODE REVIEW

File: source/jasmine/index.ts [hunk 1]
```diff
@@ -82,7 +82,10 @@ export function configure(
             )
           );
         } else {
-          t(c.name, marbles((m, ...rest: any[]) => func(m, c, ...rest)));
+          t(
```
Comment (karol-majewski) [inline source/jasmine/index.ts]: (It seems like it got autoformatted by Visual Studio Code)

File: source/jasmine/index.ts [hunk 2]
```diff
@@ -57,7 +57,7 @@ export function configure(
         defaultAssert!(a, m);
       }
     },
-    assertDeepEqual: (a, e) => expect(a).toEqual(e)
+    assertDeepEqual: (a, e) => expect(a).toStrictEqual(e)
```
Comment (cartant) [inline source/jasmine/index.ts]: AFAICT, there is no `isStrictEqual` for Jasmine, so this will have to be reverted. And if the failing test no longer fails, that will have to be removed, too.

`assertDeepEqual` is only called if the matcher sees [non-arrays](https://github.com/cartant/rxjs-marbles/blob/75b646c92765e24f42119ba1e2855946ff391811/source/matcher.ts#L81) or if the config specifies that the [framework matcher should be used](https://github.com/cartant/rxjs-marbles/blob/75b646c92765e24f42119ba1e2855946ff391811/source/matcher.ts#L64) - which is the case for Jest.

Comment (karol-majewski) [reply source/jasmine/index.ts]: Hmm, that test case does fail when I run `yarn run test:jasmine`, just the way it does for Jest. Any idea why that is?

Comment (cartant) [reply source/jasmine/index.ts]: I explained why in my comment. The test does not exercise the calling of that assertion. If you check the Jasmine docs and repo, you will see that the method does not exist.

Comment (karol-majewski) [reply source/jasmine/index.ts]: Fair enough! Reverting.

**Comment by cartant** [comment]
I'll publish a new version this evening - in about 12 hours or so - as I'm at the office, ATM.
